Feature/issue 54 replace card
okja-team/okja pull request #75
Opened 2020-03-22 15:14 UTC by gianlu92

2020-03-22 16:14 UTC, calca requested changes

2020-03-22 16:14 UTC, calca commented on mobile/src/app/modules/active-profiles/active-profiles.page.ts
> +            });
è meglio trasformarle in funzioni private in modo che il flusso sia leggibile

2020-03-22 16:14 UTC, calca commented on mobile/src/app/modules/card-profile/card-profile.component.html
> +              [src]="profileSelected.photoURL ? profileSelected.photoURL : 'assets/images/icon/ico_user_placeholder.svg'" />
non è meglio fare il check della foto nel profilo ? così dove viene usato è sempre consistente

2020-03-22 16:14 UTC, calca commented on mobile/src/app/modules/card-profile/card-profile.component.html
> +      <ion-text class="role-type-text">{{('TAB1_PAGE.ROLE_TYPE.' + entry.type) | translate}}</ion-text>
non è più TAB1

2020-03-22 16:29 UTC, citerad reviewed
![localhost_8100_(Pixel 2) (2)](https://user-images.githubusercontent.com/5503000/77254647-9e7fec80-6c62-11ea-8767-11e400f9a490.png)

2020-03-22 20:24 UTC, calca commented
@Alfr3d  com'è la UI ?

2020-03-22 21:25 UTC, calca commented
![localhost_8100_home_tabs_map(iPhone X) (3)](https://user-images.githubusercontent.com/78342/77261052-f4b55580-6c8b-11ea-96bb-703a38cdf719.png)

2020-03-23 18:02 UTC, Alfr3d commented
> @Alfr3d com'è la UI ?
in che senso?

2020-03-23 18:14 UTC, merged